version: "3.9"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
    - 127.0.0.1:8080:80
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./output/:/usr/share/nginx/html/

  # server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 127.0.0.1:8080:80
