version: "3.9"

services:
  search:
    image: chuhlomin/search:latest
    ports:
      - 127.0.0.1:8081:80
    environment:
      - INDEX_PATH=/index
      - BIND=0.0.0.0:80
    volumes:
      - ./search_index:/index
