services:
  search:
    image: getmeili/meilisearch:v1.8.0
    ports:
      - 127.0.0.1:7700:7700
    environment:
      - MEILI_MASTER_KEY
      - MEILI_NO_ANALYTICS=true
    volumes:
      - ./index:/meili_data
    command: meilisearch --env="development"
