version: "3.9"

services:
  server:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./output/:/usr/share/nginx/html/

  search:
    image: chuhlomin/search:latest
    ports:
      - 127.0.0.1:8081:80
    environment:
      - INDEX_PATH=/index
      - BIND=0.0.0.0:80
    volumes:
      - ./search_index:/index
