apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .app }}
  labels:
    app: {{ .app }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .app }}
  template:
    metadata:
      labels:
        app: {{ .app }}
    spec:
      containers:
        - name: micro
          image: {{ .image }}
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 10m
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 20Mi
        - name: search
          image: {{ .image_search }}
          ports:
            - containerPort: 8081
          resources:
            limits:
              cpu: 10m
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 20Mi
      imagePullSecrets:
        - name: ghcrcred
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .app }}
spec:
  type: ClusterIP
  selector:
    app: {{ .app }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 8081
      targetPort: 8081
