---
apiVersion: v1
kind: Secret
metadata:
  name: remark42
type: Opaque
data:
  SECRET: {{ .secret_base64 }}
  AUTH_GITHUB_CID: {{ .auth_github_cid_base64 }}
  AUTH_GITHUB_CSEC: {{ .auth_github_csec_base64 }}
  AUTH_GOOGLE_CID: {{ .auth_google_cid_base64 }}
  AUTH_GOOGLE_CSEC: {{ .auth_google_csec_base64 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .app }}
  labels:
    app: {{ .app }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .app }}
  template:
    metadata:
      labels:
        app: {{ .app }}
    spec:
      volumes:
        - name: remark42-db
          gcePersistentDisk:
            pdName: remark42-db
            fsType: ext4
        - name: remark42-backup
          gcePersistentDisk:
            pdName: remark42-backup
            fsType: ext4
      containers:
        - name: remark42
          image: {{ .image }}
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 200m
              memory: 50Mi
            requests:
              cpu: 100m
              memory: 25Mi
          env:
            - name: APP_UID
              value: "2000"
            - name: TIME_ZONE
              value: America/New_York
            - name: REMARK_URL
              value: https://comments.chuhlomin.com
            - name: STORE_BOLT_PATH
              value: /srv/var/db
            - name: BACKUP_PATH
              value: /srv/var/backup
            - name: DEBUG
              value: "{{ .remark_debug }}"
            - name: AUTH_GOOGLE_CID
              value: /srv/var/db
          envFrom:
            - secretRef:
                name: remark42
          volumeMounts:
            - name: remark42-db
              mountPath: /srv/var/db
            - name: remark42-backup
              mountPath: /srv/var/backup
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .app }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: {{ .issuer }}
spec:
  rules:
    - host: {{ .domain }}
      http:
        paths:
          - backend:
              service:
                name: {{ .name }}
                port:
                  number: 8080
            pathType: Prefix
            path: /
  tls:
    - hosts:
        - {{ .domain }}
      secretName: {{ .name }}-ingress-cert
