---
apiVersion: v1
kind: Secret
metadata:
  name: meilisearch
type: Opaque
data:
  MEILI_MASTER_KEY: {{ .meili_master_key_base64 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .app }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 7700
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .app }}
  labels:
    app: {{ .app }}
spec:
  serviceName: {{ .name }}
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .app }}
  template:
    metadata:
      labels:
        app: {{ .app }}
    spec:
      volumes:
        - name: meilisearch
          gcePersistentDisk:
            pdName: meilisearch
            fsType: ext4
      containers:
        - name: meilisearch
          image: {{ .image }}
          ports:
            - containerPort: 7700
          resources:
            limits:
              cpu: 10m
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 20Mi
          env:
            - name: MEILI_NO_ANALYTICS
              value: "true"
          envFrom:
            - secretRef:
                name: meilisearch
          volumeMounts:
            - name: meilisearch
              mountPath: /meili_data
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
    - host: {{ .domain }}
      http:
        paths:
          - backend:
              service:
                name: {{ .name }}
                port:
                  number: 8080
            pathType: Prefix
            path: /
  tls:
    - hosts:
        - {{ .domain }}
      secretName: {{ .name }}-ingress-cert
