---
apiVersion: v1
kind: Secret
metadata:
  name: remark42
type: Opaque
data:
  SECRET: {{ .secret_base64 }}
  AUTH_GITHUB_CID: {{ .auth_github_cid_base64 }}
  AUTH_GITHUB_CSEC: {{ .auth_github_csec_base64 }}
  AUTH_GOOGLE_CID: {{ .auth_google_cid_base64 }}
  AUTH_GOOGLE_CSEC: {{ .auth_google_csec_base64 }}
  TELEGRAM_TOKEN: {{ .telegram_token_base64 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .app }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .app }}
  labels:
    app: {{ .app }}
spec:
  serviceName: {{ .name }}
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .app }}
  template:
    metadata:
      labels:
        app: {{ .app }}
    spec:
      volumes:
        - name: remark42-data
          gcePersistentDisk:
            pdName: remark42-db
            fsType: ext4
        - name: remark42-backup
          gcePersistentDisk:
            pdName: remark42-backup
            fsType: ext4
      containers:
        - name: remark42
          image: {{ .image }}
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 10m
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 20Mi
          env:
            - name: APP_UID
              value: "2000"
            - name: TIME_ZONE
              value: America/New_York
            - name: REMARK_URL
              value: https://comments.chuhlomin.com
            - name: SITE
              value: "micro,micro-dev"
            - name: STORE_BOLT_PATH
              value: /srv/var/data/db
            - name: AVATAR_FS_PATH
              value: /srv/var/data/avatars
            - name: BACKUP_PATH
              value: /srv/var/backup
            - name: DEBUG
              value: "{{ .remark_debug }}"
            - name: ADMIN_SHARED_ID
              value: "{{ .admin_shared_id }}"
            - name: ADMIN_SHARED_EMAIL
              value: "{{ .admin_shared_email }}"
            - name: NOTIFY_ADMINS
              value: "telegram"
            - name: SIMPLE_VIEW
              value: "true"
            - name: EMOJI
              value: "true"
          envFrom:
            - secretRef:
                name: remark42
          volumeMounts:
            - name: remark42-data
              mountPath: /srv/var/data
            - name: remark42-backup
              mountPath: /srv/var/backup
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
    - host: {{ .domain }}
      http:
        paths:
          - backend:
              service:
                name: {{ .name }}
                port:
                  number: 8080
            pathType: Prefix
            path: /
  tls:
    - hosts:
        - {{ .domain }}
      secretName: {{ .name }}-ingress-cert
