apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .app }}
  labels:
    app: {{ .app }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .app }}
  template:
    metadata:
      labels:
        app: {{ .app }}
    spec:
      containers:
        - name: micro
          image: {{ .image }}
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 20m
              memory: 50Mi
            requests:
              cpu: 10m
              memory: 10Mi
      imagePullSecrets:
        - name: ghcrcred
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .app }}
spec:
  type: ClusterIP
  selector:
    app: {{ .app }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
