name: main

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: ghcr.io/chuhlomin/micro
  DOCKER_IMAGE_SEARCH: ghcr.io/chuhlomin/micro_search

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: GenBlog
        uses: chuhlomin/genblog@v0.5
        with:
          title: Konstantin Chukhlomin's microblog
          author: Konstantin Chukhlomin
          short_description: ""
          output_directory: "./output"
          templates_directory: "./templates"
          source_directory: "."
          allowed_file_extensions: ".jpeg,.jpg,.png,.mp4,.pdf"
          typography_enabled: "false"
          comments_enabled: "true"
          comments_site_id: "micro"
          search_enabled: "true"
          search_path: "search_index"

      - name: Build and push to CR (server)
        uses: chuhlomin/actions/docker-build-push@main
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PKG_TOKEN }}
          image_name: ${{ env.DOCKER_IMAGE }}
          tags: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

      - name: Build and push to CR (search)
        uses: chuhlomin/actions/docker-build-push@main
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PKG_TOKEN }}
          image_name: ${{ env.DOCKER_IMAGE_SEARCH }}
          dockerfile: search.dockerfile
          tags: ${{ env.DOCKER_IMAGE_SEARCH }}:${{ github.sha }}

      - name: Deploy to GKE
        uses: chuhlomin/actions/deploy-gke@main
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
          cluster_name: cluster-east
          location: us-east4-c
          template_path: kube.template.yml
          vars: |
            image: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
            image_search: ${{ env.DOCKER_IMAGE_SEARCH }}:${{ github.sha }}
            app: micro
            replicas: 2
          rollout_status_wait: deployment/micro
