name: main

on:
  push:
    branches:
      - refactor/generator
      # - main

env:
  DOCKER_IMAGE_SEARCH: ghcr.io/chuhlomin/micro_search

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        env:
          ROOT_URL: https://homepage-bqu.pages.dev/
          REMOVE_HTML_EXT: "1"
          COMMENTS_ENABLED: "1"
          COMMENTS_SITE_ID: "micro"
          SEARCH_ENABLED: "0"
          # SEARCH_URL: "https://chuhlomin.com/blog/search/?q="
        run:
          make build

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages publish output --project-name=homepage --env=production --branch=main --commit-dirty=true

      # - name: Build and push to CR (search)
      #   uses: chuhlomin/actions/docker-build-push@main
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.PKG_TOKEN }}
      #     image_name: ${{ env.DOCKER_IMAGE_SEARCH }}
      #     dockerfile: search.dockerfile
      #     tags: ${{ env.DOCKER_IMAGE_SEARCH }}:${{ github.sha }}

      # - name: Deploy to GKE
      #   uses: chuhlomin/actions/deploy-gke@main
      #   with:
      #     service_account_key: ${{ secrets.GKE_SA_KEY }}
      #     project_id: ${{ secrets.GKE_PROJECT }}
      #     cluster_name: cluster-east
      #     location: us-east4-c
      #     template_path: kube.template.yml
      #     vars: |
      #       image: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
      #       image_search: ${{ env.DOCKER_IMAGE_SEARCH }}:${{ github.sha }}
      #       app: micro
      #       replicas: 2
      #     rollout_status_wait: deployment/micro
