name: main

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: cache
          key: ${{ runner.os }}-cache

      - name: Build
        env:
          ROOT_URL: https://chuhlomin.com
          REMOVE_HTML_EXT: "1"
          COMMENTS_ENABLED: "1"
          COMMENTS_SITE_ID: "micro"
          SEARCH_ENABLED: "1"
          SEARCH_HOST: "https://search.chuhlomin.com/"
          SEARCH_MASTER_KEY: ${{ secrets.SEARCH_MASTER_KEY }}
          SEARCH_API_KEY: ${{ secrets.SEARCH_API_KEY }}
        run:
          make build

      - name: Publish
        uses: cloudflare/wrangler-action@3.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages publish output --project-name=homepage --branch=main --commit-dirty=true
