name: main

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@0057852bfaa89a56745cba8c7296529d2fc39830 # v4

      - name: Restore cache
        uses: actions/cache@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          path: cache
          key: ${{ runner.os }}-cache

      - name: Setup Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6
        with:
          go-version-file: generator/go.mod

      - name: Build
        env:
          ROOT_URL: https://chuhlomin.com
          REMOVE_HTML_EXT: "1"
          COMMENTS_ENABLED: "1"
          COMMENTS_SITE_ID: "micro"
          SEARCH_ENABLED: "1"
          SEARCH_HOST: "https://search.chuhlomin.com/"
          SEARCH_MASTER_KEY: ${{ secrets.SEARCH_MASTER_KEY }}
          SEARCH_API_KEY: ${{ secrets.SEARCH_API_KEY }}
        run:
          make build

      - name: Deploy
        uses: cloudflare/wrangler-action@a84dcc6dd36c8769fbff7e622308c8050fc41f4f # v3.5.0
        if: github.event_name == 'push' && !contains(github.event.head_commit.message, '[skip deploy]')
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy output --project-name=homepage --branch=main --commit-dirty=true
