name: main

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: mkdir -p output output/2020 output/2021; cp templates/styles.css output/styles.css

      - name: GenBlog
        uses: chuhlomin/genblog@v0.1
        with:
          title: "Konstantin Chukhlomin's microblog"
          author: "Konstantin Chukhlomin"
          short_description: ""
          posts_directory: "."
          output_directory: "output"
