name: meilisearch

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/meilisearch.yml
      - kube-meilisearch.template.yml
  workflow_dispatch:

jobs:
  meilisearch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to GKE
        uses: chuhlomin/actions/deploy-gke@main
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
          cluster_name: cluster-east
          location: us-east4-c
          template_path: kube-meilisearch.template.yml
          vars: |
            image: getmeili/meilisearch:v1.2.0
            name: meilisearch
            app: meilisearch
            replicas: 1
            domain: search.chuhlomin.com
            meili_master_key_base64: ${{ secrets.SEARCH_MASTER_KEY_BASE64 }}
          rollout_status_wait: sts/meilisearch
