name: remark42

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/remark42.yml
      - kube-remark42.template.yml
  workflow_dispatch:

jobs:
  remark42:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to GKE
        uses: chuhlomin/actions/deploy-gke@main
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
          cluster_name: cluster-east
          location: us-east4-c
          template_path: kube-remark42.template.yml
          vars: |
            image: umputun/remark42:v1.10.1
            name: remark42
            app: remark42
            replicas: 1
            domain: comments.chuhlomin.com
            remark_debug: "false"
            admin_shared_id: "github_273bcb28a295b223235763996744e39f7cedfbc4"
            admin_shared_email: ${{ secrets.ADMIN_SHARED_EMAIL }}
            secret_base64: ${{ secrets.REMARK42_SECRET_BASE64 }}
            auth_github_cid_base64: ${{ secrets.AUTH_GITHUB_CID_BASE64 }}
            auth_github_csec_base64: ${{ secrets.AUTH_GITHUB_CSEC_BASE64 }}
            auth_google_cid_base64: ${{ secrets.AUTH_GOOGLE_CID_BASE64 }}
            auth_google_csec_base64: ${{ secrets.AUTH_GOOGLE_CSEC_BASE64 }}
            telegram_token_base64: ${{ secrets.TELEGRAM_TOKEN_BASE64 }}
            admin_passwd_base64: ${{ secrets.ADMIN_PASSWD_BASE64 }}
          rollout_status_wait: sts/remark42
