name: screenshot

on:
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Make screenshot
        uses: chuhlomin/actions/screenshot@main
        with:
          url: file://${{github.workspace}}/output/index.html
          mode: wholePage
          output: screenshot.png
          width: 800
          height: 600
          deviceScaleFactor: 2
          cornerRadius: 20
          addShadow: true
          commit: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
